Chistyakov patch 1
nats-io/nats.docs pull request #242
Opened 2021-04-14 12:48 UTC by mxchist

Add an information about issues which I have encounter during the set up NATS logging. This is:

* preferable location of the log file;
* setting up pid file
* setting up the log rotation with the `logrotate`

2021-04-15 16:15 UTC, ColinSullivan1 requested changes
Thanks for the contribution!  Much appreciated!  

This looks good, with a few minor changes requested.  Longer term, the NATS streaming server is being deprecated in favor of JetStream, so references to nats-streaming-server would not age well (this is just being announced).  Would you mind changing the nats-streaming-server references?

2021-04-15 16:15 UTC, ColinSullivan1 commented on nats-server/configuration/logging.md
> +    create 644 nss nss
I would suggest renaming this from `nss` to something different, like or `nats`.  Longer term, the NATS streaming server is being deprecated in favor of [JetStream](https://docs.nats.io/jetstream/jetstream), so nss may not make as much sense in the future (assuming nss represents the user for nats-streaming-server).

2021-04-15 16:15 UTC, ColinSullivan1 commented on nats-server/configuration/logging.md
> +* If you encounter a failure after enable logrotate for nats, with the following error message: `nats-streaming-server[pid]: Could not write pidfile: open /var/run/nats-server.pid: permission denied`
Per the comment above, would you mind changing this to `nats-server`?

2021-11-04 15:52 UTC, gcolliso commented
@mxchist Could you review the comments from @ColinSullivan1 for this PR and let me know if it is still needed or updated?

2023-03-26 17:42 UTC, closed without merging