translate overview and welcome page to Chinese
nats-io/nats.docs pull request #417
Opened 2022-04-28 17:08 UTC by xieyuschen

Hi, I have translated the `overview` and `welcome` pages to Chinese. 
@gcolliso @matthiashanel 

Would I ask to you for writing permission from a branch so that I could manage the translation process for the Chinese version?

Thanks for your review and maintenance.

2022-05-20 13:04 UTC, xieyuschen commented
Hi @matthiashanel , @gcolliso . Could you review it and how do you think the docs in Chinese?

2022-05-25 13:55 UTC, gcolliso commented
@xieyuschen we don't have anyone on our team to review in Chinese. Would you have a co-worker or colleague that would be able to review?

2022-05-25 14:04 UTC, xieyuschen commented
> @xieyuschen we don't have anyone on our team to review in Chinese. Would you have a co-worker or colleague that would be able to review?

Yes, it's my honor to work with you as a colleague to review the Chinese version.

2022-05-25 15:41 UTC, xieyuschen commented
> @xieyuschen we don't have anyone on our team to review in Chinese. Would you have a co-worker or colleague that would be able to review?

yup, I would like to invite my friends to co-work with the docs.
Let me check with him.

2022-05-25 15:48 UTC, xieyuschen commented
> @xieyuschen we don't have anyone on our team to review in Chinese. Would you have a co-worker or colleague that would be able to review?

To be honest, the work for documents might be boring especially in reviewing. 

I think we can also get help from the people who read our docs.

2022-05-26 02:45 UTC, FanHengbo commented
Thanks for the invitation from @xieyuschen !
Hi @gcolliso , I think I might be able to review the Chinese translation.

2022-05-26 03:44 UTC, FanHengbo commented on zh-cn/overview.md
> +**轻易联通M:N模型两端：** NATS的寻址与服务发现基于主题，而不是传统的主机名或者端口。默认采取1:1模型的超集，也就是M：N模型进行通信，
NATS的寻址与服务发现采用了基于主题的模式， 而并非像传统模式一样使用主机名和端口号

2022-05-26 03:51 UTC, FanHengbo commented on zh-cn/overview.md
> +**轻易联通M:N模型两端：** NATS的寻址与服务发现基于主题，而不是传统的主机名或者端口。默认采取1:1模型的超集，也就是M：N模型进行通信，
```suggestion
**轻易联通M:N模型两端：** NATS的寻址与服务发现采用基于主题的模式，而不是像传统模式一样使用主机名和端口。默认采取1:1模型的超集，也就是M：N模型进行通信，
```

2022-05-26 03:58 UTC, FanHengbo commented on zh-cn/overview.md
> +这可以让他在1:1模型下做到更多的事情。如你在开发一个1:1模型的系统，请思考该系统需要多少额外的部分才可以绕开1:1的模型，如负载均衡器，日志系统
```suggestion
这可以让它在1:1模型下做到更多的事情。例如你在开发一个1:1模型的系统，请思考该系统需要多少额外的部分才能在1:1模型的假设下运转，如负载均衡器，日志系统
```

2022-05-26 04:03 UTC, FanHengbo commented on zh-cn/overview.md
> +**安全：** 相似的，NATS默认安全，不依赖于外部网络安全模型。很多时候，当你开始考虑后端微服务或者流式处理服务时，安全是一个相当重要的指标。
```suggestion
**安全性：** 相似的，NATS在不依赖于外部网络安全模型的前提下是默认安全的，很多时候，当你开始考虑后端微服务或者流式处理服务时，安全是一个相当重要的指标。  
```

2022-05-26 04:07 UTC, FanHengbo commented on zh-cn/overview.md
> +NATS可以在任何地方允许，从大型服务器和云实例到边缘网关设备甚至物联网设备。NATS的使用场景包括：
```suggestion
从大型服务器和云实例到边缘网关设备甚至物联网设备，NATS可以在任何地方运行。NATS的使用场景包括：
```

2022-05-26 04:08 UTC, FanHengbo commented on zh-cn/overview.md
> +    * 事件/数据流（观察，分析，加强学习与人工智能）
```suggestion
    * 事件/数据流（观察，分析，机器学习/人工智能）
```

2022-05-26 04:09 UTC, FanHengbo commented on zh-cn/overview.md
> +这可以让他在1:1模型下做到更多的事情。如你在开发一个1:1模型的系统，请思考该系统需要多少额外的部分才可以绕开1:1的模型，如负载均衡器，日志系统
```suggestion
这可以让它在1:1模型下做到更多的事情。如你在开发一个1:1模型的系统，请思考该系统需要多少额外的部分才可以绕开1:1的模型，如负载均衡器，日志系统
```

2022-05-26 04:16 UTC, FanHengbo requested changes
I've left some comments and suggestions that should be addressed before these two translations get merged.

2022-05-26 08:16 UTC, xieyuschen commented
> I've left some comments and suggestions that should be addressed before these two translations get merged.

Fixed it, thanks.

2022-05-26 08:19 UTC, FanHengbo approved these changes

2022-05-26 11:58 UTC, xieyuschen commented
@gcolliso I have invited my co-worker to review it, I think it is ok now.
Thanks

2022-06-06 03:45 UTC, Billdex commented
Hello! I'm the author of issue #381 . I was pause the plan because of personal reason.
Today I try to restart translating work and notice this PR. I would join the translation.

Thanks for your work.

2022-06-06 09:08 UTC, xieyuschen commented
> Hello! I'm the author of issue #381 . I was pause the plan because of personal reason. Today I try to restart translating work and notice this PR. I would join the translation.
> 
> Thanks for your work.


Thanks, welcome to work together.

2022-07-11 10:35 UTC, closed without merging