Add a doc with JetStream troubleshooting hints
nats-io/nats.docs pull request #525
Opened 2022-11-02 23:32 UTC by rodrigc

I put this doc together based on feedback in this Slack thread:
https://natsio.slack.com/archives/C02JR4XSA5B/p1666905105421849?thread_ts=1666904875.388139&cid=C02JR4XSA5B

2022-11-09 16:48 UTC, gcolliso commented
Thanks @rodrigc! 
@jnmoyne or @codegangsta could you review and provide comments and/or approval?

2022-11-18 18:26 UTC, bruth requested changes
Thanks for putting this together! A few minor adjustments, but otherwise looks good.

2022-11-18 18:26 UTC, bruth commented on running-a-nats-service/configuration/clustering/jetstream_clustering/troubleshooting.md
> +* knowledge of [JetStream concepts](/nats-concepts/jetstream/#jetstream-1)
```suggestion
* knowledge of [JetStream concepts](../../../../nats-concepts/jetstream/readme.md)
```

2022-11-18 18:26 UTC, bruth commented on running-a-nats-service/configuration/clustering/jetstream_clustering/troubleshooting.md
> +| [nats account info](../../../nats_admin/jetstream_admin/account.md) | Verify that JetStream is enabled on account |
```suggestion
| [`nats account info`](../../../nats_admin/jetstream_admin/account.md) | Verify that JetStream is enabled on account |
```

2022-11-18 18:26 UTC, bruth commented on running-a-nats-service/configuration/clustering/jetstream_clustering/troubleshooting.md
> +|  [nats server check](../../../clients.md#testing-your-setup) | Health check for NATS servers |
```suggestion
|  [`nats server check`](../../../clients.md#testing-your-setup) | Health check for NATS servers |
```

2022-11-18 18:26 UTC, bruth commented on running-a-nats-service/configuration/clustering/jetstream_clustering/troubleshooting.md
> +| [nats server report jetstream](./administration.md#viewing-the-cluster-state) | Report on JetStream activity |
```suggestion
| [`nats server report jetstream`](./administration.md#viewing-the-cluster-state) | Report on JetStream activity |
```

2022-11-18 18:26 UTC, bruth commented on running-a-nats-service/configuration/clustering/jetstream_clustering/troubleshooting.md
> +|  [nats server request jetstream](./administration.md#viewing-the-cluster-state) | Show JetStream details |
```suggestion
|  [`nats server request jetstream`](./administration.md#viewing-the-cluster-state) | Show JetStream details |
```

2022-11-18 21:15 UTC, rodrigc commented
@bruth I incorporated all your suggestions

2022-11-18 21:17 UTC, jnmoyne commented
LGTM

2022-11-18 21:20 UTC, jnmoyne approved these changes

2022-11-18 22:59 UTC, bruth approved these changes

2022-11-19 01:49 UTC, merged